-- AlterTable
ALTER TABLE "Order" ALTER COLUMN "delivery_fee" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "OrderItem" ALTER COLUMN "variant_1_price" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "variant_2_price" SET DATA TYPE DOUBLE PRECISION;
